dependencies:
- name: nginx-ingress
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~0.22.0
- name: cert-manager
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: ~0.5.0