web:
  domain: web.gofigure.local
  development_volume: /c/ImparaAi/go-figure-web
  env:
    safe:
      DEVELOPMENT: true
backend:
  domain: backend.gofigure.local
  development_volume: /c/ImparaAi/go-figure-backend
  env:
    safe:
      DEVELOPMENT: true