apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.web.https }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-cluster-issuer
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ required "web.domain value required" .Values.web.domain }}
    secretName: tls-go-figure-web
  rules:
  - host: {{ required "web.domain value required" .Values.web.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
        {{- if .Values.web.safe_environments.DEVELOPMENT }}
          servicePort: 4200
        {{- else }}
          servicePort: 80
        {{- end }}
