apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 4200
    targetPort: angular-dev
    name: angular-dev
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: web