apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.backend.https }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-cluster-issuer
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ required "backend.domain value required" .Values.backend.domain }}
    secretName: tls-go-figure-backend
  rules:
  - host: {{ required "backend.domain value required" .Values.backend.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80