apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  web.conf: |
    server {
      listen 80;
      server_name {{ .Values.web.domain }};

      location / {

        return 200 'test';

        {{- if .Values.web.env.safe.DEVELOPMENT }}
          proxy_pass http://web:4200;
        {{- else }}
          proxy_pass http://web:80;
        {{- end }}
      }
    }

    server {
      listen 80;
      server_name {{ .Values.backend.domain }};

      location / {
        proxy_pass http://backend:80;
      }
    }
