apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  web.conf: |
    server {
      listen 80;
      server_name {{ .Values.web.domain }};

      location / {
        return 200 'port 80';
        proxy_pass http://web:80;
      }
    }

    server {
      listen 4200;
      server_name {{ .Values.web.domain }};

      location / {
        return 200 'port 4200';
        proxy_pass http://web:4200;
      }
    }
