apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.0-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
          - name: nginx-vhost
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-vhost
        configMap:
          name: nginx-config