apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: http
  - port: 4200
    targetPort: http-angular
  selector:
    app: nginx
  type: NodePort