apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: angular-cli
    protocol: TCP
    port: 4200
    targetPort: angular-cli
  selector:
    app: nginx
  type: NodePort