apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  {{- if .Values.api.development_volume }}
  replicas: 1
  {{- else }}
  replicas: 2
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/api/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: api
        {{- if .Values.api.development_volume }}
        image: imparaai/go-figure-api:dev
        {{- else }}
        image: imparaai/go-figure-api
        {{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - cat
            - /var/healthy
          initialDelaySeconds: 3
          periodSeconds: 3
        envFrom:
          - secretRef:
              name: api-secrets
      {{- if .Values.api.development_volume }}
        volumeMounts:
          - name: api
            mountPath: /go/src/app
      volumes:
      - name: api
        hostPath:
          path: {{ .Values.api.development_volume }}
      {{- end }}