apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.api.https }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ required "api.domain value required" .Values.api.domain }}
    secretName: tls-go-figure-api
  rules:
  - host: {{ required "api.domain value required" .Values.api.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 80