apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  serviceName: api
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: api
        image: imparaai/go-figure-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          exec:
            command:
            - cat
            - /var/healthy
          initialDelaySeconds: 3
          periodSeconds: 3
        envFrom:
          - configMapRef:
              name: api-config
        volumeMounts:
          - name: sqlite-data
            mountPath: /go/src/app/database/sqlite
      {{- if .Values.api.development_volume }}
          - name: api
            mountPath: /go/src/app
      volumes:
      - name: api-dev
        hostPath:
          path: {{ .Values.api.development_volume }}
      {{- end }}
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: sqlite-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi